import { TabContainer } from "tabs.slint";
import { Theme, TimerConfig, TimerType, TimerAction } from "globals.slint";

export component SlidingTransition {
    in-out property <bool> expanded;
    out property <length> continuation-x;

    in-out property <bool> active;
    in-out property <duration> target-time;
    in-out property <TimerType> active-timer;
    in-out property <int> active-round;
    in-out property <duration> remaining-time;
    in-out property <TimerConfig> timer-config: tab-container.timer-config;
    in-out property <image> circle-progress;

    callback action-timer(TimerAction);

    animate continuation-x {
        duration: 300ms;
        easing: ease-in-out;
    }

    states [
        vis when root.expanded: {
            continuation-x: 0;
        }
        not-vis when !root.expanded: {
            continuation-x: self.width * -1;
        }
    ]

    horizontal-stretch: 0;

    Rectangle {
        y: 0;
        x: root.continuation-x;
        height: 100%;
        width: 100%;

        content := Rectangle {
            clip: true;

            tab-container := TabContainer {
                active: root.active;
                target-time: root.target-time;
                remaining-time: root.remaining-time;
                active-timer: root.active-timer;
                active-round: root.active-round;

                circle-progress: root.circle-progress;

                action-timer(action) => { root.action-timer(action) }
            }
        }
    }
}